Update AccountLink.swift
vapor-community/stripe-kit pull request #101
Opened 2020-08-05 16:04 UTC by Maxim-Inv

Updated according the last information from doc - https://stripe.com/docs/api/account_links/create

2020-08-08 01:27 UTC, Andrewangeta commented
@Maxim-Inv  Will add this to the next major release since this is breaking, I just released a major version 8.0.0 and stripe still accepts the previous parameters.

2020-09-21 22:57 UTC, Andrewangeta requested changes

2020-09-21 22:57 UTC, Andrewangeta commented on Sources/StripeKit/Connect/Account Links/AccountLink.swift
> +	/// Provides a form for inputting outstanding requirements. Send the user to the form in this mode to just collect the new information you need.
@Maxim-Inv Can we fix the indentation here?

2020-09-21 22:57 UTC, Andrewangeta commented on Sources/StripeKit/Errors/StripeError.swift
> +	case testModeLiveCard = "test_mode_live_card"
Same with indentation.

2020-09-21 22:57 UTC, Andrewangeta commented on Sources/StripeKit/Errors/StripeError.swift
> +		case .testModeLiveCard: return "The customer should use a test card https://stripe.com/docs/testing#cards"
indentation.

2020-09-22 15:30 UTC, Maxim-Inv commented
@Andrewangeta Sorry, I have been little busy. But now I have fixed it.

2020-09-22 15:31 UTC, Andrewangeta approved these changes

2020-09-22 15:31 UTC, merged