This func should be mutating func
vapor-community/stripe-kit pull request #126
Opened 2021-04-22 07:46 UTC by varungakhar

2021-04-22 12:26 UTC, Andrewangeta commented
What the actual issue here? The screenshot you posted has no context?

2021-04-22 18:20 UTC, varungakhar commented
when i am trying to create file , i am getting this error
 request.stripe.files.create(file: document_id, purpose: .identityDocument)

2021-04-22 18:39 UTC, Andrewangeta commented
What's the actual error? None of the other functions on any other API route needs to be a `mutating func` so why is this one the exception? I need a clear error as to what's  actually happening first.

2021-04-22 18:44 UTC, Andrewangeta commented
I see, it's because the implementation itself is a `mutating func` because it modifies the `headers` property in the `struct` itself but the protocol extension isn't mutating.

2021-04-22 18:45 UTC, Andrewangeta requested changes

2021-04-22 18:45 UTC, Andrewangeta commented on Sources/StripeKit/Core Resources/Files/FileRoutes.swift
> +   mutating func create(file: Data, purpose: StripeFilePurpose, fileLinkData: [String: Any]?) -> EventLoopFuture<StripeFile>
Small indentation here.

2021-04-29 15:54 UTC, Andrewangeta approved these changes

2021-04-29 22:13 UTC, merged