Fixed Allowed Documents mapping for Stripe Identity
vapor-community/stripe-kit pull request #231
Opened 2023-08-21 13:20 UTC by dbossotto

Fix #230

2023-08-21 15:37 UTC, Andrewangeta requested changes

2023-08-21 15:37 UTC, Andrewangeta commented on Sources/StripeKit/Identity/VerificationSession/VerificationSession.swift
> +    case idNumber = "id_card"
Can you change the name of the enum here as well?

2023-08-22 09:53 UTC, dbossotto commented
I've pushed a new commit to implement the changes you requested:
    case idCard = "id_card"

2023-08-22 17:47 UTC, Andrewangeta approved these changes

2023-08-22 18:01 UTC, merged